export const authConstant = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
  ALL_CATEGORIES: "ALL_CATEGORIES",
  GET_SINGLE_CATEGORIES: "GET_SINGLE_CATEGORIES",
  ADD_TO_CART:"ADD_TO_CART",
  REMOVE_TO_CART:"REMOVE_TO_CART"

};
